version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds.json
      - OPENAI_API_KEY=<your_openai_api_key_here>
    volumes:
      - type: bind
        source: /mnt/
        target: /app
    command: "npm start"
